---
# user

- name: Create user
  user:
    name: "{{ item.name }}"
    comment: "{{ item.state | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    createhome: '{{ item.createhome | default("yes") }}'
    home: '{{ item.home | default("/home/"~item.name) }}'
    shell: '{{ item.shell | default("/bin/bash") }}'
    generate_ssh_key: '{{ item.generate_ssh_key | default("no") }}'
    state: '{{ item.state | default("present") }}'
    append: yes
  become: yes
  with_items:
  - "{{ user }}"
  tags:
  - create_user
