---
# directory

- name: Create directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
  - "{{ directory }}"
  tags:
  - create_directory
